
INSERT INTO public.funcionarios (nome, cpf, cargo, status) VALUES
('Adner Gelumer', '00100100101', 'Vigilante', 'Ativo'),
('Andrea Melo da Silva Roxinski', '00200200202', 'Vigilante', 'Ativo'),
('Andrey Nunes dos Santos', '00300300303', 'Vigilante', 'Ativo'),
('Anouse Petit Frere', '00400400404', 'Vigilante', 'Ativo'),
('Antonio Airton Melo da Silva', '00500500505', 'Vigilante', 'Ativo'),
('Bianca de Oliveira da Luz', '00600600606', 'Vigilante', 'Ativo'),
('Carlos Sampaio de Araujo', '00700700707', 'Vigilante', 'Ativo'),
('Claudia Aparecida Neri Lobo', '00800800808', 'Vigilante', 'Ativo'),
('Cleusa Perpetuo de Lima', '00900900909', 'Vigilante', 'Ativo'),
('Derondes Gomes da Silva Bezerra', '01001001010', 'Vigilante', 'Ativo'),
('Eilzo Lopes da Silva', '01101101111', 'Vigilante', 'Ativo'),
('Eliane dos Santos Almeida', '01201201212', 'Vigilante', 'Ativo'),
('Emerson Nunes dos Santos', '01301301313', 'Vigilante', 'Ativo'),
('Eric Luiz Pinto', '01401401414', 'Vigilante', 'Ativo'),
('Everton Olimpio', '01501501515', 'Vigilante', 'Ativo'),
('Every Leidy Quijada Farias', '01601601616', 'Vigilante', 'Ativo'),
('Frank Frederik Gascon David', '01701701717', 'Vigilante', 'Ativo'),
('Gabrielle Vitoria Monteiro Melanski', '01801801818', 'Vigilante', 'Ativo'),
('Gilberto Zarnott', '01901901919', 'Vigilante', 'Ativo'),
('Gilmara Cordeiro dos Santos Gonçalves', '02002002020', 'Vigilante', 'Ativo'),
('Glaucia Michele Dias Gonçalves', '02102102121', 'Vigilante', 'Ativo'),
('Gustavo Garczeski Soares', '02202202222', 'Vigilante', 'Ativo'),
('Hercules Leonel da Silva', '02302302323', 'Vigilante', 'Ativo'),
('Jean Carlos Jimenez', '02402402424', 'Vigilante', 'Ativo'),
('Jennifer Fernanda Penteado Rodrigues', '02502502525', 'Vigilante', 'Ativo'),
('Jessica Suelen Silva', '02602602626', 'Vigilante', 'Ativo'),
('Jeysi Carolina Serrano Ugas', '02702702727', 'Vigilante', 'Ativo'),
('Jorge Luis Castro Rondon', '02802802828', 'Vigilante', 'Ativo'),
('José Ramos Goes da Silva', '02902902929', 'Vigilante', 'Ativo'),
('Joselito Alexsandro da Silva', '03003003030', 'Vigilante', 'Ativo'),
('Josner Jean Louis', '03103103131', 'Vigilante', 'Ativo'),
('Juan Antônio Oropeza Hernández', '03203203232', 'Vigilante', 'Ativo'),
('Leonardo Fernandes', '03303303333', 'Vigilante', 'Ativo'),
('Leticia Maiara de Melo Silva', '03403403434', 'Vigilante', 'Ativo'),
('Luixibeth Del Valle Aleman Penalver', '03503503535', 'Vigilante', 'Ativo'),
('Luiz Alberto Perinotti', '03603603636', 'Vigilante', 'Ativo'),
('Maicon de Paulo Taborda', '03703703737', 'Vigilante', 'Ativo'),
('Manassés dos Santos', '03803803838', 'Vigilante', 'Ativo'),
('Marcio Patrick Batista Valadares', '03903903939', 'Vigilante', 'Ativo'),
('Marcos Aurelio Vieira', '04004004040', 'Vigilante', 'Ativo'),
('Maria Eduarda Antunes dos Santos', '04104104141', 'Vigilante', 'Ativo'),
('Mariana Pontaldi Balbi', '04204204242', 'Vigilante', 'Ativo'),
('Marieli Leviske', '04304304343', 'Vigilante', 'Ativo'),
('Marina Maximiano Rocha', '04404404444', 'Vigilante', 'Ativo'),
('Max Willian Ciqueira', '04504504545', 'Vigilante', 'Ativo'),
('Nivaldo Aparecido de Lara Machado', '04604604646', 'Vigilante', 'Ativo'),
('Norgis Charleron', '04704704747', 'Vigilante', 'Ativo'),
('Osvaldo Romanio', '04804804848', 'Vigilante', 'Ativo'),
('Pedro Augusto Benicio Silva', '04904904949', 'Vigilante', 'Ativo'),
('Pedro Jose Jimenez Sosa', '05005005050', 'Vigilante', 'Ativo'),
('Petiel Jean', '05105105151', 'Vigilante', 'Ativo'),
('Rafael Augusto de Oliveira', '05205205252', 'Vigilante', 'Ativo'),
('Renata Pereira', '05305305353', 'Vigilante', 'Ativo'),
('Ricardo Enrique Millan Andrades', '05405405454', 'Vigilante', 'Ativo'),
('Robert José Arrieta Ali', '05505505555', 'Vigilante', 'Ativo'),
('Roseli Pereira', '05605605656', 'Vigilante', 'Ativo'),
('Ruben Dario Perez Granados', '05705705757', 'Vigilante', 'Ativo'),
('Russerbin Azucena Briceño Diaz', '05805805858', 'Vigilante', 'Ativo'),
('Sara Mizael Pereira de Oliveira Smaniotto', '05905905959', 'Vigilante', 'Ativo'),
('Silvio de Souza', '06006006060', 'Vigilante', 'Ativo'),
('Taise Alves de Cristo Monteiro', '06106106161', 'Vigilante', 'Ativo'),
('Tamiris de Fatima Sizanovski', '06206206262', 'Vigilante', 'Ativo'),
('Tchano Romeu', '06306306363', 'Vigilante', 'Ativo'),
('Thiago dos Santos Almeida', '06406406464', 'Vigilante', 'Ativo'),
('Victor Manuel Ortiz Gonzalez', '06506506565', 'Vigilante', 'Ativo'),
('Wislande Joseph', '06606606666', 'Vigilante', 'Ativo');

-- Insert quality forms
INSERT INTO public.formularios_qualidade (codigo, titulo, revisao, categoria, campos) VALUES
('DC.RH.001', 'Descrição Cargo', 'rev.01', 'rh', '[{"nome":"cargo","tipo":"text","label":"Cargo"},{"nome":"departamento","tipo":"text","label":"Departamento"},{"nome":"supervisor","tipo":"text","label":"Supervisor Imediato"},{"nome":"resumo","tipo":"textarea","label":"Resumo do Cargo"},{"nome":"responsabilidades","tipo":"textarea","label":"Responsabilidades"},{"nome":"requisitos","tipo":"textarea","label":"Requisitos"},{"nome":"competencias","tipo":"textarea","label":"Competências"}]'::jsonb),
('FOR.RH.001', 'Medida Disciplinar', 'rev.00', 'rh', '[{"nome":"funcionario","tipo":"text","label":"Funcionário"},{"nome":"data","tipo":"date","label":"Data"},{"nome":"tipo_medida","tipo":"select","label":"Tipo de Medida","opcoes":["Advertência Verbal","Advertência Escrita","Suspensão","Desligamento"]},{"nome":"motivo","tipo":"textarea","label":"Motivo"},{"nome":"descricao","tipo":"textarea","label":"Descrição dos Fatos"},{"nome":"testemunhas","tipo":"text","label":"Testemunhas"},{"nome":"observacoes","tipo":"textarea","label":"Observações"}]'::jsonb),
('FOR.RH.002', 'Entrevista de Desligamento', 'rev.01', 'rh', '[{"nome":"funcionario","tipo":"text","label":"Funcionário"},{"nome":"data_admissao","tipo":"date","label":"Data de Admissão"},{"nome":"data_desligamento","tipo":"date","label":"Data de Desligamento"},{"nome":"motivo","tipo":"select","label":"Motivo do Desligamento","opcoes":["Pedido de Demissão","Demissão sem Justa Causa","Demissão por Justa Causa","Acordo"]},{"nome":"avaliacao_empresa","tipo":"textarea","label":"Avaliação da Empresa"},{"nome":"sugestoes","tipo":"textarea","label":"Sugestões de Melhoria"}]'::jsonb),
('FOR.RH.003', 'Plano Anual Treinamento', 'rev.00', 'rh', '[{"nome":"ano","tipo":"text","label":"Ano Referência"},{"nome":"departamento","tipo":"text","label":"Departamento"},{"nome":"treinamentos","tipo":"textarea","label":"Treinamentos Planejados"},{"nome":"cronograma","tipo":"textarea","label":"Cronograma"},{"nome":"orcamento","tipo":"text","label":"Orçamento Estimado"}]'::jsonb),
('FOR.RH.004', 'Registro Treinamento', 'rev.00', 'rh', '[{"nome":"treinamento","tipo":"text","label":"Nome do Treinamento"},{"nome":"data","tipo":"date","label":"Data"},{"nome":"instrutor","tipo":"text","label":"Instrutor"},{"nome":"carga_horaria","tipo":"text","label":"Carga Horária"},{"nome":"participantes","tipo":"textarea","label":"Participantes"},{"nome":"conteudo","tipo":"textarea","label":"Conteúdo Programático"}]'::jsonb),
('FOR.RH.007', 'Abertura Vaga', 'rev.02', 'rh', '[{"nome":"cargo","tipo":"text","label":"Cargo"},{"nome":"departamento","tipo":"text","label":"Departamento"},{"nome":"motivo","tipo":"select","label":"Motivo","opcoes":["Substituição","Aumento de Quadro","Nova Função"]},{"nome":"requisitos","tipo":"textarea","label":"Requisitos"},{"nome":"salario","tipo":"text","label":"Faixa Salarial"},{"nome":"urgencia","tipo":"select","label":"Urgência","opcoes":["Alta","Média","Baixa"]}]'::jsonb),
('FOR.RH.010', 'Avaliação Desempenho', 'rev.01', 'rh', '[{"nome":"funcionario","tipo":"text","label":"Funcionário"},{"nome":"periodo","tipo":"text","label":"Período Avaliado"},{"nome":"pontualidade","tipo":"select","label":"Pontualidade","opcoes":["Excelente","Bom","Regular","Insuficiente"]},{"nome":"produtividade","tipo":"select","label":"Produtividade","opcoes":["Excelente","Bom","Regular","Insuficiente"]},{"nome":"comportamento","tipo":"select","label":"Comportamento","opcoes":["Excelente","Bom","Regular","Insuficiente"]},{"nome":"observacoes","tipo":"textarea","label":"Observações"},{"nome":"plano_acao","tipo":"textarea","label":"Plano de Ação"}]'::jsonb),
('FOR.RH.015', 'Programação de Férias', 'rev.01', 'rh', '[{"nome":"funcionario","tipo":"text","label":"Funcionário"},{"nome":"periodo_aquisitivo","tipo":"text","label":"Período Aquisitivo"},{"nome":"data_inicio","tipo":"date","label":"Início das Férias"},{"nome":"data_fim","tipo":"date","label":"Fim das Férias"},{"nome":"abono","tipo":"select","label":"Abono Pecuniário","opcoes":["Sim","Não"]}]'::jsonb),
('FOR.RH.016', 'Ficha de Solicitação de Emprego', 'rev.01', 'rh', '[{"nome":"nome","tipo":"text","label":"Nome Completo"},{"nome":"cpf","tipo":"text","label":"CPF"},{"nome":"rg","tipo":"text","label":"RG"},{"nome":"endereco","tipo":"text","label":"Endereço"},{"nome":"telefone","tipo":"text","label":"Telefone"},{"nome":"cargo_pretendido","tipo":"text","label":"Cargo Pretendido"},{"nome":"experiencia","tipo":"textarea","label":"Experiência Profissional"},{"nome":"escolaridade","tipo":"text","label":"Escolaridade"}]'::jsonb),
('FOR.RH.017', 'Ficha Entrega EPI', 'rev.02', 'rh', '[{"nome":"funcionario","tipo":"text","label":"Funcionário"},{"nome":"data","tipo":"date","label":"Data"},{"nome":"itens","tipo":"textarea","label":"Itens Entregues (EPI)"},{"nome":"observacoes","tipo":"textarea","label":"Observações"}]'::jsonb),
('FOR.RH.023', 'Matriz de Treinamento', 'rev.00', 'rh', '[{"nome":"departamento","tipo":"text","label":"Departamento"},{"nome":"treinamentos","tipo":"textarea","label":"Treinamentos Obrigatórios"},{"nome":"periodicidade","tipo":"text","label":"Periodicidade"},{"nome":"responsavel","tipo":"text","label":"Responsável"}]'::jsonb),
('FOR.RH.025', 'Programação Demissões', 'rev.01', 'rh', '[{"nome":"funcionario","tipo":"text","label":"Funcionário"},{"nome":"data_prevista","tipo":"date","label":"Data Prevista"},{"nome":"motivo","tipo":"textarea","label":"Motivo"},{"nome":"tipo","tipo":"select","label":"Tipo","opcoes":["Sem Justa Causa","Por Justa Causa","Acordo"]},{"nome":"observacoes","tipo":"textarea","label":"Observações"}]'::jsonb),
('FOR.RH.027', 'Análise DISC', 'rev.00', 'rh', '[{"nome":"funcionario","tipo":"text","label":"Funcionário"},{"nome":"dominancia","tipo":"text","label":"Dominância (D)"},{"nome":"influencia","tipo":"text","label":"Influência (I)"},{"nome":"estabilidade","tipo":"text","label":"Estabilidade (S)"},{"nome":"conformidade","tipo":"text","label":"Conformidade (C)"},{"nome":"perfil","tipo":"textarea","label":"Perfil Predominante"},{"nome":"recomendacoes","tipo":"textarea","label":"Recomendações"}]'::jsonb);
