// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pugkwannvnkskgyxldnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1Z2t3YW5udm5rc2tneXhsZG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwOTkyMjIsImV4cCI6MjA4ODY3NTIyMn0._ilo0aCVjHi88fXgpdDd-ISHKnT4rAQ3_jh2m2CE2yE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});